"""ERDiagram → Mermaid ERD 텍스트 변환기.

파서(mermaid.py)와 동일한 dialect를 사용해야 라운드트립이 성립한다.
label은 역방향 파싱에서 복원 불가능하므로 "relates" 기본값을 사용한다.
"""
from src.ir.models import ERDiagram, RelationType

_ARROW = {
    RelationType.ONE_TO_ONE:   "||--||",
    RelationType.ONE_TO_MANY:  "||--o{",
    RelationType.MANY_TO_ONE:  "}o--||",
    RelationType.MANY_TO_MANY: "}o--o{",
}


def to_mermaid(diagram: ERDiagram) -> str:
    lines = [
        "%%  auto-generated by erd-to-api reverse parser",
        "%%  relation labels are not recoverable from code — edit as needed",
        "erDiagram",
    ]

    for entity in diagram.entities:
        lines.append(f"  {entity.name} {{")
        for f in entity.fields:
            tags: list[str] = []
            if f.primary_key:
                tags.append("PK")
            if f.foreign_key:
                tags.append("FK")
            tag_str = (" " + " ".join(tags)) if tags else ""
            lines.append(f"    {f.type.value} {f.name}{tag_str}")
        lines.append("  }")

    for rel in diagram.relations:
        arrow = _ARROW.get(rel.type, "||--o{")
        label = rel.label or "relates"
        lines.append(f'  {rel.from_entity} {arrow} {rel.to_entity} : "{label}"')

    return "\n".join(lines)
